### ISSUE TITLE
Build fails when I tried to disable exceptions with XTENSOR_DISABLE_EXCEPTIONS

### ISSUE THREAD

**Issue by luk036** [xtensor-stack/xtensor-blas#171]
When I tried to disable exceptions by setting the `XTENSOR_DISABLE_EXCEPTIONS` macro, I found that xtensor-blas` did not follow the rule. When I replace the statement:

`throw std::runtime_error(`

with

`XTENSOR_THROW(std::runtime_error, `

in all files, it works.

**Comment by JohanMabille** [comment]
Thanks for reporting. That's indeed a feature we forgot to implement in xtenosr-blas.

**Comment by JohanMabille** [comment]
Fixed in #172
