### ISSUE TITLE
-march=native is not supported on all architectures

### ISSUE THREAD

**Issue by drew-parsons** [xtensor-stack/xtensor-blas#196]
The xtensor-blas tests add a "-march=native" flag on non-Win32 systems, both gcc and clang, at ll.60,69 in test/CMakeLists.txt.

But this flag is not universal, and so the test build fails on most non-amd64 architectures, e.g.  [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=xtensor-blas&arch=ppc64el&ver=0.19.0-1&stamp=1618057870&raw=0), [ia64](https://buildd.debian.org/status/fetch.php?pkg=xtensor-blas&arch=ia64&ver=0.19.0-1&stamp=1617960980&raw=0), [riscv64](https://buildd.debian.org/status/fetch.php?pkg=xtensor-blas&arch=riscv64&ver=0.19.0-1&stamp=1617965282&raw=0).  Build logs can be found at https://buildd.debian.org/status/package.php?p=xtensor-blas&suite=experimental, and some test logs at https://ci.debian.net/packages/x/xtensor-blas/

The problem has been dealt with in [xtensor](https://github.com/xtensor-stack/xtensor/blob/869cc0a22aea80d34f0728e184842bdea42fe43b/test/CMakeLists.txt#L70), which tests for the flag and defines `arch_native_supported` before conditionally adding it to `CMAKE_CXX_FLAGS`.

**Comment by james-d-mitchell** [comment]
I had the same exact issue, I guess this is simple to resolve @wolfv @SylvainCorlay @JohanMabille would a pr fixing this be welcome?

**Comment by wolfv** [comment]
yes!
