### ISSUE TITLE
Can you please create a conan package for this

### ISSUE THREAD

**Issue by ansar-sa** [xtensor-stack/xtensor-blas#199]
Current build systems already using conan. xtensor is available on conan but not xtensor-blas.
Can xtensor-blas and the xtensor-stack please also be made available in conan center. Thank you!

**Comment by JohanMabille** [comment]
Hello, conan packages can be created independently. They are out of the scope of the xtensor source repositories . I think it would be better to contact the people who already maintain the packages for the other libraries of the xtensor-stack and ask them to add xtensor-blas to the package list.
