### ISSUE TITLE
Could NOT find BLAS (missing: BLAS_LIBRARIES)

### ISSUE THREAD

**Issue by 3e33** [xtensor-stack/xtensor-blas#230]
`find_package(OpenBLAS)` works in my own CMakeLists, but because `xtensor-blasConfig.cmake` has `find_dependency(BLAS)` it fails there.

`xtensor-blas/lib/cmake/xtensor-blas/xtensor-blasConfig.cmake:47 (find_dependency)`

I've already tried `set(BLA_VENDOR OpenBLAS)` and the [settings in the documentation ](https://xtensor-blas.readthedocs.io/en/latest/performance.html)and all of it fails.

**Comment by 3e33** [comment]
I managed to fix this by adding `list(APPEND CMAKE_PREFIX_PATH <PATH TO FOLDER YOU INSTALLED OpenBLAS INTO>)`.
If anyone knows a less hacky way though please let me know.

**Comment by stellarpower** [comment]
Good catch, I was trying to do the same in my CMakeLists, and this seems to go against the docs as you linked. Typical CMake dependencies mess :roll_eyes: 

This worked for me. Even without the edits to the cmake config file. I am using mamba for managing dependencies and buildtools, and CMake version 3.25.2:
```cmake
find_package( BLAS REQUIRED )
message( STATUS BLAS found: ${BLAS_LIBRARIES} )
list(APPEND Libraries ${BLAS_LIBRARIES})

find_package(xtensor-blas     REQUIRED)
include_directories(${xtensor-blas_INCLUDE_DIRS})
list(APPEND Libraries    xtensor-blas)
```

In theory this is doing the same as you tried (and I tried myself from the xtensor-blas docs), so not sure what has gone on there - but I was googling and landed here:
https://cmake.org/cmake/help/latest/module/FindBLAS.html

I presume this is hooking into a script provided by CMake to find a vendor-neutral BLAS, which (for me at least) is then setting things up correctly. OpenBLAS is in the mamba environment, so this may be faciitated by not having any other BLAS implementations in the search path.

**Comment by 3e33** [comment]
@stellarpower Sorry I think I made my comment confusing, I edited it now. The path in `CMAKE_PREFIX_PATH` needs to be the path *into* the OpenBLAS folder. It's not simply "where it's installed", but it needs to be the actual folder, that's the only way it's working for me if I have OpenBLAS downloaded by itself, not using package managers like mamba.
